/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Matheus
 */
public class Pagamento_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Pagamento_GUI
     */
    public Pagamento_GUI() {
        initComponents();
        carregarPedido();
    }
    
    private void gerarPDF(String senha) {
    try {
        String caminho = System.getProperty("user.home") + 
            "/Desktop/pedido_" + senha.replace("#", "") + ".pdf";

        com.itextpdf.text.Document documento = 
            new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(
            documento, new java.io.FileOutputStream(caminho));

        documento.open();

        // Título
        com.itextpdf.text.Font fonteTitulo = new com.itextpdf.text.Font(
            com.itextpdf.text.Font.FontFamily.HELVETICA, 20,
            com.itextpdf.text.Font.BOLD);
        documento.add(new com.itextpdf.text.Paragraph(
            "QuickBite — Seu Lanche, do Seu Jeito", fonteTitulo));
        documento.add(new com.itextpdf.text.Paragraph(" "));

        // Senha
        com.itextpdf.text.Font fonteSenha = new com.itextpdf.text.Font(
            com.itextpdf.text.Font.FontFamily.HELVETICA, 16,
            com.itextpdf.text.Font.BOLD);
        documento.add(new com.itextpdf.text.Paragraph(
            "Senha: " + senha, fonteSenha));
        documento.add(new com.itextpdf.text.Paragraph(" "));

        // Tipo de consumo
        documento.add(new com.itextpdf.text.Paragraph(
            "Tipo: " + Model.SessaoPedido.getPedido().getTipoConsumo()));
        documento.add(new com.itextpdf.text.Paragraph(
            "Pagamento: " + Model.SessaoPedido.getFormaPagamento()));
        documento.add(new com.itextpdf.text.Paragraph(" "));

        // Itens
        documento.add(new com.itextpdf.text.Paragraph("Itens do pedido:"));
        for (Model.Produto p : Model.SessaoPedido.getPedido().getItens()) {
            documento.add(new com.itextpdf.text.Paragraph(
                "  - " + p.getNome() + 
                "  (" + String.format("R$ %.2f", p.getPreco()) + ")"));
        }
        documento.add(new com.itextpdf.text.Paragraph(" "));

        // Total
        com.itextpdf.text.Font fonteTotal = new com.itextpdf.text.Font(
            com.itextpdf.text.Font.FontFamily.HELVETICA, 14,
            com.itextpdf.text.Font.BOLD);
        documento.add(new com.itextpdf.text.Paragraph(
            "Total: " + String.format("R$ %.2f", 
            Model.SessaoPedido.getPedido().calcularTotal()), fonteTotal));

        documento.close();

        javax.swing.JOptionPane.showMessageDialog(this,
            "Pedido confirmado!\nSenha: " + senha + 
            "\nComprovante salvo na Área de Trabalho.");

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Erro ao gerar PDF: " + e.getMessage());
    }
}

    private void carregarPedido() {
        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (Model.Produto p : Model.SessaoPedido.getPedido().getItens()) {
            modelo.addRow(new Object[]{
                p.getNome(),
                p.getCategoria(),
                String.format("R$ %.2f", p.getPreco())
            });
        }

        double total = Model.SessaoPedido.getPedido().calcularTotal();
        totalTxt.setText(String.format("R$ %.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        a = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_esticada.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(170, 0, 330, 80);

        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao-voltar.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(7, 23, 130, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 80);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 180, 550, 170);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pagamento");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(261, 100, 160, 33);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seu pedido:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 150, 140, 26);

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton8.setText("Cancelar pedido");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(60, 710, 220, 60);

        jButton7.setBackground(new java.awt.Color(51, 255, 51));
        jButton7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton7.setText("Confirmar Pagamento");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(390, 710, 230, 60);

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cifrao.png"))); // NOI18N
        jButton2.setText("Dinheiro");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(440, 490, 140, 120);

        jButton3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pix.png"))); // NOI18N
        jButton3.setText("Pix");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(90, 490, 140, 120);

        jButton4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartao-do-banco.png"))); // NOI18N
        jButton4.setText("Cartão");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(260, 490, 140, 120);

        a.setBackground(new java.awt.Color(255, 255, 255));
        a.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jLabel5.setText("Total:");
        a.add(jLabel5);
        jLabel5.setBounds(10, 20, 70, 29);

        totalTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a.add(totalTxt);
        totalTxt.setBounds(130, 10, 80, 40);

        jPanel1.add(a);
        a.setBounds(70, 370, 240, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(700, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Principal_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Model.SessaoPedido.setFormaPagamento("PIX");
javax.swing.JOptionPane.showMessageDialog(this, "Pagamento via PIX selecionado!");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Model.SessaoPedido.setFormaPagamento("CARTAO");
javax.swing.JOptionPane.showMessageDialog(this, "Pagamento via Cartão selecionado!");// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Model.SessaoPedido.setFormaPagamento("DINHEIRO");
javax.swing.JOptionPane.showMessageDialog(this, "Pagamento em Dinheiro selecionado!");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
    "Deseja cancelar o pedido?", "Cancelar",
    javax.swing.JOptionPane.YES_NO_OPTION);
if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
    Model.SessaoPedido.limpar();
    Model.SessaoPedido.novoPedido();
    new View.Tela_avanço_GUI().setVisible(true);
    this.dispose();
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (Model.SessaoPedido.getFormaPagamento() == null) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Selecione uma forma de pagamento!");
    return;
}

// Gera a senha
Controller.PedidoController pc = new Controller.PedidoController();
String senha = pc.gerarSenha();
Model.SessaoPedido.getPedido().setSenha(senha);
Model.SessaoPedido.getPedido().setFormaPagamento(
    Model.SessaoPedido.getFormaPagamento());

// Salva no banco
int id = pc.salvarPedido(Model.SessaoPedido.getPedido());

if (id == -1) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Erro ao salvar pedido. Tente novamente.");
    return;
}

// Gera o PDF
gerarPDF(senha);

// Reseta a sessão
Model.SessaoPedido.limpar();
Model.SessaoPedido.novoPedido();

// Volta pra tela inicial
new View.Tela_avanço_GUI().setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagamento_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel a;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel totalTxt;
    // End of variables declaration//GEN-END:variables
}
